config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/Home'

  get 'static_pages/Help'
  
  get 'static_pages/goofy'

  resources :microposts
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#Home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/micropost.rb
class Micropost < ApplicationRecord
    belongs_to :user
    validates :content, length: {maximum: 140 },
                        presence: true 
end

app/models/user.rb
class User < ApplicationRecord
  has_many :microposts
  validates :name, length: { minimum: 1 }, 
  presence: true
  validates :email, length: { minimum: 1 },
  presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  def hello
      render html: "hello, world!"
  end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :set_micropost, only: [:show, :edit, :update, :destroy]

  # GET /microposts
  # GET /microposts.json
  def index
    @microposts = Micropost.all
  end

  # GET /microposts/1
  # GET /microposts/1.json
  def show
  end

  # GET /microposts/new
  def new
    @micropost = Micropost.new
  end

  # GET /microposts/1/edit
  def edit
  end

  # POST /microposts
  # POST /microposts.json
  def create
    @micropost = Micropost.new(micropost_params)

    respond_to do |format|
      if @micropost.save
        format.html { redirect_to @micropost, notice: 'Micropost was successfully created.' }
        format.json { render :show, status: :created, location: @micropost }
      else
        format.html { render :new }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /microposts/1
  # PATCH/PUT /microposts/1.json
  def update
    respond_to do |format|
      if @micropost.update(micropost_params)
        format.html { redirect_to @micropost, notice: 'Micropost was successfully updated.' }
        format.json { render :show, status: :ok, location: @micropost }
      else
        format.html { render :edit }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /microposts/1
  # DELETE /microposts/1.json
  def destroy
    @micropost.destroy
    respond_to do |format|
      format.html { redirect_to microposts_url, notice: 'Micropost was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_micropost
      @micropost = Micropost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def micropost_params
      params.require(:micropost).permit(:content, :user_id)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def Home
  end

  def Help
  end
  
  def goofy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Imran's Portfolio</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  </head>
  <body class = "container">
    <div class = "page-header">
      <ul class="nav nav-tabs" role="tablist">
        <li role="presentation" class= "active"><a href = "/">Home</a></li>
        <li role="presentation"><a href="/microposts">About</a></li>
        <li role"presentation"><a href="/static_pages/Help">Portfolio</a></li>
      </ul>
    </div>
    <%= yield %>
  </body>
</html> 

app/views/microposts/_form.html.erb
<%= form_for(micropost) do |f| %>
  <% if micropost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(micropost.errors.count, "error") %> prohibited this micropost from being saved:</h2>

      <ul>
      <% micropost.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.number_field :user_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/microposts/edit.html.erb
<h1>Editing Micropost</h1>

<%= render 'form', micropost: @micropost %>

<%= link_to 'Show', @micropost %> |
<%= link_to 'Back', microposts_path %>

app/views/microposts/index.html.erb
<!DOCTYPE html>
    <html>
        <head>
            <meta charset="utf-8">
            <style>
              body{background-color: #B6B8BA;}
            </style>
            <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
            <script>
            /*function that executes when page is fully loaded */
            $(document).ready(
                function()
                {
                    $('img[id^="imran"]').width(200).height(200);
                }
                );
            </script>
        </head>
        <body>
            <div id="main">
                <article>
                <h2>My Journey</h2>
                <p><img src= "imran.jpg" alt= "Imran Sandozi" id="imran">Hi my name is Imran Sandozi and this is my journey how I became passionate about design. Design is one of the many forms of development in the major sector that is Information Technology. Its main focus is to "connect" a user with a "product." It is my goal to provide this experience to a user to become as seamless as possible.
                </p>
                <p>
                    Growing up, I can always remember trying to figure out how things were working. With the arrival of technological devices such as PCs, Laptops, Smart Phones, and Tablets my curiosity soared.
                </p>
                <p>
                    Away from the classroom, the sector that is Information Technology has had an everlasting, satisfying part of my personality. I find it very rare not to have at least my tablet to experience some new code. Whether it be debugging a program I am writing in JavaScript or learning new stacks for development, I was lucky early in my journey to learn the importance of innovation and design.
                </p>
                <h2>Who I Am</h2>
                <p>
                    From the beginning, I am and always have been an eager person. I may ask an unlimited number of questions to find how things work or to understand how things work. To create an everlasting impact, there needs to be understanding of what we are creating, how they work, and the most efficient way to perform action.
                </p>
                <p>
                    I enjoy learning new technologies. Whether it be how it works or how it can be better, I am devoted to put the two together, helping others around me, and becoming extremely successful through my work.
                </p>
                <h2>What I Believe</h2>
                <p>Designing solutions to what has been given to me has been rewarding yet satisfying. However, I feel I was put in this world to help others with the knowledge and skills I have been blessed with. I am devoted to help others conquer their tasks ranging from a miniscule goal to an extraordinary level revolutionizing our industry. I have found myself most effective when communicating with others regarding how to make their day to day easier for their family. If we are able to make a difference in one person's life for the better not only do we advance, but the world advances.
                </p>
                <h3>
                    Let's do something great.
                </h3>
                <h1>Imran Sandozi</h1>
                <hr>
                <h2>References</h2>
                <p class="bold">
                    "Imran performed exceedingly well in web design and incorporates visual design and programming principles.
On a few occasions, he came up with excellent questions leading to reflection and clarification. With a similar effort to other endeavors, he will do extremely well."<br><br>-Joseph Mendelsohn, Professional Lecturer, DePaul University</p><br><br>
                </article>
            </div>
    </body>
    </html>

app/views/microposts/new.html.erb
<h1>New Micropost</h1>

<%= render 'form', micropost: @micropost %>

<%= link_to 'Back', microposts_path %>

app/views/microposts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @micropost.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @micropost.user_id %>
</p>

<%= link_to 'Edit', edit_micropost_path(@micropost) %> |
<%= link_to 'Back', microposts_path %>

app/views/static_pages/Help.html.erb
<!DOCTYPE html>
    <html>
        <head>
            <meta charset="utf-8">
            <style>
                p{font-family: lucida sans; font-size: 18px; line-height: 20px; margin-left: 40px; color:#170146; float: right;}

img{float: left; padding-right: 25px;}

body{background-color: #B6B8BA;}

div#main {position: static;width: 2000px; height: 1000px;
        margin-left: auto; margin-right: auto;}
        
article{position: relative;width: 900px; height: 750px; overflow: hidden; margin-left: auto; margin-right: auto;}

div#game{position: absolute; background-color: red; height: 200px; width: 200px; top: 450px; left: 500px; border: 3px solid red; border-radius: 100%;}

div#dice{position: absolute; background-color: orange; height: 200px; width: 200px; top: 175px; left: 650px; border: 3px solid orange; border-radius: 100%;}

div#myvision{position: absolute; background-color: blue;height: 200px; width: 200px; top: 175px; left: 50px; border: 3px solid blue; border-radius: 100%;}

div#myapplication{position: absolute; background-color: green; height: 200px; width: 200px; top: 175px; left: 350px;border: 3px solid green; border-radius: 100%;}

div#chicago{position: absolute; background-color: purple; height: 200px; width: 200px; top: 450px; left: 200px; border: 3px solid purple; border-radius: 100%;}

h1{color:#AF0408; letter-spacing:5px; text-shadow: 8px 8px 20px #000000; font-size: 40px; font-family: Edwardian Script ITC; text-align: left;}

h2{color: #AF0408; font-size: 70px; font-family: Edwardian Script ITC; text-align: center; letter-spacing: 5px;}

.circle{position: relative; width: 100%; height: 0; color: white; font-family: lucida sans; font-size: 30px; text-align: center; line-height: 5;}
            </style>
        </head>
        <body>
            <div id="main">
                <article>
                    <h2>Welcome</h2>
               
                   <a href="a6.html" target= "_blank"><div id="myvision" class="circle">
                    My Story
                   </div></a>
               
                    <a href="interactive_application.html" target = "_blank"><div id="myapplication" class="circle">
                        Apply!!
                  </div></a>
               
                    <a href="a8/a8.html" target= "_blank"><div id="dice" class="circle">
                        Play Dice!
                    </div></a>

                    <a href="a5.html" target= "_blank"><div id="chicago" class="circle">
                        Chicago!
                    </div></a>
            
                    <a href="psr/psr.html" target= "_blank"><div id="game" class="circle">
                        P.S.R.!
                    </div></a>
                </article>
            </div>
    </body>
    </html>

app/views/static_pages/Home.html.erb
<!DOCTYPE html>
    <html>
        <head>
            <meta charset="utf-8">
            <title>
                Imran Sandozi's Portfolio
            </title>
            <style>
                p{color:white; font-family: lucida sans; font-size: 18px;
                    line-height: 20px;}
                body {background-image: url("color-background-image.jpg");
      background-position: center center;
      background-repeat: no-repeat;
      background-attachment: fixed;
      background-size: cover;
}
a {font-size: 24px; font-family: lucida sans;
    text-decoration: none; padding: 10px; line-height: 36px;
    font-weight: bold;}
                a:link {color:white;}
                a:hover {color: white; background-color: lightblue;
                border-width: 1px; border-style: solid; border-color: lightblue;
                border-radius: 10px;}
                a:active {color:red; background-color: black;
                text-decoration: none;}
                a:visited{color: white;}
                div#main {position: static;
                          width: 800px; height: 800px;
                          margin-left: auto;
                          margin-right: auto;}
                article{position: static;
                        width: 750px; height: 650px; float: left;
                        overflow: auto; padding-left: 25px; padding-right: 25px;
                        text-align: justify;}
                h1{color: white; font-size: 80px; font-family: Edwardian Script ITC; text-align: left; letter-spacing: 5px;}
                h2{color: white; font-size: 50px; font-family: Edwardian Script ITC; text-align: left;}
            </style>
        </head>
        <body>
            <div id="main">
                <article><br><br><br><br>
                <p>
                    Hi, my name is Imran Sandozi and I help create <strong>interaction</strong>. I believe design means creating things that connects people and influences behavior.</p>
                <p>I have a strong passion for problem solving and believe that problem solving and connecting with people are essential for society to progress.<br><br>Welcome to my portfolio. I look forward to working together.</p>
                    <h1>Imran Sandozi</h1>
                </article>
            </div>
    </body>
    </html>

app/views/static_pages/goofy.html.erb
<h1>Goofy StaticPages#goofy</h1>
<p>Contact Me at the following email address:</p>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><button type="button" class= "btn btn-xs btn-danger"><%= link_to 'Show', user %></button></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>